import re

# should chinese punctuation be spaced?
punctuation_string = "?!.\u060c\u061F"
quoted_pattern_maybe_space = re.compile(r'\"\s?([^"]*?)\s?\"')
english_regex = re.compile(r"([a-zA-Z\-][a-zA-Z_\-'s\.:]*[_0-9]?||\b[a-z0-9]*\b|\d+|'s)")
english_person_names = re.compile(r"\b(\w+\s\w(?!\s\.))\b")

quoted_pattern_no_space = re.compile(r'\"([^"]*?)\"')
quoted_pattern_with_space = re.compile(r'\"\s([^"]*?)\s\"')
quoted_number_pattern = re.compile(r'\"\s(\d{1,2})\s\"')
duration_date_time_number_pattern = re.compile(r'(DURATION_\d|DATE_\d|TIME_\d|NUMBER_\d)', re.IGNORECASE)
# duration_or_date_pattern_lowercase = re.compile(r'duration_\d|date_\d')
multiple_space_pattern = re.compile(r'\s{2,}')

entity_pattern = re.compile(r'([A-Z][A-Z_]*_[0-9]+|GENERIC_ENTITY_[a-zA-Z\.:\d]+)')
only_generic_entity_pattern = re.compile(r'(GENERIC_ENTITY_[a-zA-Z\.:\d]+)')
id_number_pattern = re.compile(r'([0-9]+)')
number_pattern = re.compile(r'\b([0-9]+)\b')
small_number_pattern = re.compile(r'\b([0-9])\b')

quoted_pattern_maybe_space_or_number = re.compile(r'\"\s?([^"]*?)\s?\"|(?<!\[\s)([0-9]+)')

# WOZ ontologies

# BiTOD_ZH_DOMAINS = {
#     'zh': ("餐厅", "宾馆", "景点", "天气", "香港地铁", "聊天", 'chat'),
#     'en': ('restaurants', 'hotels', 'attractions', 'weathers', 'HKMTR', 'chat'),
# }
#
# BiTOD_ZH_INTENTS = {
#     'zh': ('确认', '报价', '通知'),
#     'en': ('Confirm', 'Quote', 'Notice'),
# }
#
# BiTOD_ZH_SLOTS = {
#     'zh': ('房间数', '天气', '参考编号', '可用选项', '预估时间', '时间', '名字', '日期', '人数', '开始日期', '最高温度',
#            '电话', '价格', '预订天数', '城市', '每晚价格', '最短路线', '地址', '预订日期', '最低温度', '菜品', '评分'),
#     'en': ('number of rooms','weather','reference number','available options','estimated time',
#            'time','name','date','number of people','start date','maximum temperature ','phone','price',
#            'booking days','city','price per night','shortest route','address','booking date','minimum temperature','dishes','score'),
# }

BiTOD_EN_DOMAINS = {
    'en': ('restaurants', 'hotels', 'attractions', 'weathers', 'HKMTR', 'chat'),
    'zh': ("餐馆", "宾馆", "景点", "天气", "香港地铁", 'chat'),
    'de': ('Restaurants', 'Hotels', 'Attraktionen', 'Wetter', 'HK MTR', 'Chat'),
}
BiTOD_EN_INTENTS = {
    'en': (
        'inform',
        'confirm',
        'offer',
        'request',
        'request_more',
        'greeting',
        'affirm',
        'notify_success',
        'notify_fail',
        'goodbye',
        'request_update',
    ),
    'zh': ('通知', '确认', '报价', '要求', '要求更多', '问候', '肯定', '通知成功', '通知失败', '再见', '请求更新'),
    'de': (
        'informieren',
        'bestätigen',
        'anbieten',
        'anfordern',
        'mehr_anfordern',
        'Grüße',
        'bekräftigen',
        'Erfolg_benachrichtigen',
        'Fehlschlag_benachrichtigen',
        'Auf_Wiedersehen',
        'Update_anfordern',
    ),
}

BiTOD_EN_SLOTS = {
    'en': (
        'null',
        'booking_date',
        'date',
        'estimated_time',
        'price',
        'shortest_path',
        'start_date',
        'name',
        'location',
        'rating',
        'type',
        'address',
        'phone_number',
        'available_options',
        'ref_number',
        'price_per_night',
        'user_name',
        'number_of_rooms',
        'start_month',
        'start_day',
        'number_of_nights',
        'price_level',
        'stars',
        'cuisine',
        'dietary_restrictions',
        'day',
        'city',
        'max_temp',
        'min_temp',
        'weather',
        'description',
        'departure',
        'destination',
        'number_of_people',
        'time',
    ),
    'zh': (
        "空值",
        "预订日期",
        "日期",
        "预估时间",
        "价格",
        "最短路线",
        '开始日期',
        '名字',
        '位置',
        '评分',
        '类别',
        '地址',
        '电话',
        '可用选项',
        '参考编号',
        '每晚价格',
        '用户名',
        '房间数',
        '预订月',
        '预订日',
        '预订天数',
        '价格范围',
        '星级数',
        '菜品',
        '饮食限制',
        '日',
        '城市',
        '最高温度',
        '最低温度',
        '天气',
        '描述',
        '出发地',
        '目的地',
        '人数',
        '时间',
    ),
    'de': (
        'null',
        'Buchungsdatum',
        'Datum',
        'geschätzte_Zeit',
        'Preis',
        'kürzester_Weg',
        'Startdatum',
        'Name',
        'Ort',
        'Bewertung',
        'Typ',
        'Adresse_',
        'Telefonnummer',
        'Verfügbare_Optionen',
        'Referenznummer',
        'Preis_pro_Nacht',
        'Benutzername',
        'Anzahl_Zimmer',
        'Startmonat',
        'Starttag',
        'Anzahl_der_Nächte',
        'Preisniveau',
        'Sterne',
        'Küche',
        'Ernährungsbeschränkungen',
        'Tag',
        'Stadt',
        'max_temp',
        'min_temp',
        'Wetter',
        'Beschreibung',
        'Abfahrt',
        'Ziel',
        'Anzahl_Personen',
        'Zeit',
    ),
}

SGD_DOMAINS = {
    'en': (
        'restaurant_2',
        'flight_3',
        'ridesharing_1',
        'rentalcar_1',
        'bus_1',
        'alarm_1',
        'services_4',
        'weather_1',
        'home_1',
        'bank_2',
        'travel_1',
        'movie_2',
        'media_2',
        'hotel_4',
        'hotel_1',
        'music_1',
        'event_1',
        'restaurant_1',
        'media_1',
        'event_2',
        'music_2',
        'movie_1',
        'flight_1',
        'flight_2',
        'ridesharing_2',
        'rentalcar_2',
        'bus_2',
        'hotel_2',
        'services_2',
        'services_1',
        'services_3',
        'bank_1',
        'calendar_1',
        'hotel_3',
        'music_3',
        'event_3',
        'flight_4',
        'rentalcar_3',
        'bus_3',
        'home_2',
        'payment_1',
        'train_1',
        'movie_3',
        'media_3',
        'messaging_1',
    ),
    'fa': (
        'رستوران_2',
        'پرواز_3',
        'اشتراک_در_مسافرت_1',
        'اجاره_اتومبیل_1',
        'اتوبوس_1',
        'زنگ_خطر_1',
        'خدمات_4',
        'هوا_1',
        'خانه_1',
        'بانک_2',
        'سفر_1',
        'فیلم_2',
        'رسانه_2',
        'هتل_4',
        'هتل_1',
        'موسیقی_1',
        'رویداد_1',
        'رستوران_1',
        'رسانه_1',
        'رویداد_2',
        'موسیقی_2',
        'فیلم_1',
        'پرواز_1',
        'پرواز_2',
        'اشتراک_گذاری_ماشین_2',
        'اجاره_ماشین_2',
        'اتوبوس_2',
        'هتل_2',
        'خدمات_2',
        'خدمات_1',
        'خدمات_3',
        'بانک_1',
        'تقویم_1',
        'هتل_3',
        'موسیقی_3',
        'رویداد_3',
        'پرواز_4',
        'اجاره_ماشین_3',
        'اتوبوس_3',
        'خانه_2',
        'پرداخت_1',
        'قطار_1',
        'فیلم_3',
        'رسانه_3',
        'پیام_رسانی_1',
    ),
}

SGD_1_DOMAINS = {
    'en': (
        'Restaurants_2',
        'Flights_3',
        'RideSharing_1',
        'RentalCars_1',
        'Buses_1',
        'alarm_1',
        'Services_4',
        'weather_1',
        'Homes_1',
        'Banks_2',
        'Travel_1',
        'Movies_2',
        'Media_2',
        'Hotels_4',
        'Hotels_1',
        'Music_1',
        'Events_1',
        'Restaurants_1',
        'Media_1',
        'Events_2',
        'Music_2',
        'Movies_1',
        'Flights_1',
        'Flights_2',
        'RideSharing_2',
        'RentalCars_2',
        'Buses_2',
        'Hotels_2',
        'Services_2',
        'Services_1',
        'Services_3',
        'Banks_1',
        'Calendar_1',
        'Hotels_3',
        'Music_3',
        'Events_3',
        'Flights_4',
        'RentalCars_3',
        'Buses_3',
        'Homes_2',
        'Payment_1',
        'Trains_1',
        'Movies_3',
        'Media_3',
        'Messaging_1',
    ),
    'fa': (
        'رستوران_2',
        'پرواز_3',
        'اشتراک_در_مسافرت_1',
        'اجاره_اتومبیل_1',
        'اتوبوس_1',
        'زنگ_خطر_1',
        'خدمات_4',
        'هوا_1',
        'خانه_1',
        'بانک_2',
        'سفر_1',
        'فیلم_2',
        'رسانه_2',
        'هتل_4',
        'هتل_1',
        'موسیقی_1',
        'رویداد_1',
        'رستوران_1',
        'رسانه_1',
        'رویداد_2',
        'موسیقی_2',
        'فیلم_1',
        'پرواز_1',
        'پرواز_2',
        'اشتراک_گذاری_ماشین_2',
        'اجاره_ماشین_2',
        'اتوبوس_2',
        'هتل_2',
        'خدمات_2',
        'خدمات_1',
        'خدمات_3',
        'بانک_1',
        'تقویم_1',
        'هتل_3',
        'موسیقی_3',
        'رویداد_3',
        'پرواز_4',
        'اجاره_ماشین_3',
        'اتوبوس_3',
        'خانه_2',
        'پرداخت_1',
        'قطار_1',
        'فیلم_3',
        'رسانه_3',
        'پیام_رسانی_1',
    ),
}

SGD_INTENTS = {
    'en': ('inform_intent', 'inform_count', 'request', 'offer', 'select', 'inform', 'confirm', 'offer_intent', 'service_call'),
    'fa': ("اطلاع_قصد", "اطلاع_تعداد", "درخواست", "پیشنهاد", "انتخاب", "اطلاع", "تأیید", "پیشنهاد_قصد", "سرویس_تماس"),
}

SGD_SPECIAL_INTENTS = {
    'en': ('req_more', 'notify_failure', 'notify_success', 'goodbye'),
    'fa': ("درخواست_بیشتر", "اطلاع_عدم_موفقیت", "اطلاع_موفقیت", "خداحافظ"),
}

SGD_1_INTENTS = {
    'en': ('INFORM_INTENT', 'INFORM_COUNT', 'REQUEST', 'OFFER', 'SELECT', 'INFORM', 'CONFIRM', 'OFFER_INTENT', 'service_call'),
    'fa': ("اطلاع_قصد", "اطلاع_تعداد", "درخواست", "پیشنهاد", "انتخاب", "اطلاع", "تأیید", "پیشنهاد_قصد", "سرویس_تماس"),
}

SGD_1_SPECIAL_INTENTS = {
    'en': ('REQ_MORE', 'NOTIFY_FAILURE', 'NOTIFY_SUCCESS', 'GOODBYE'),
    'fa': ("درخواست_بیشتر", "اطلاع_عدم_موفقیت", "اطلاع_موفقیت", "خداحافظ"),
}

SGD_SLOTS = {
    'en': (
        'number_of_adults',
        'song_name',
        'refundable',
        'aggregate_rating',
        'street_address',
        'show_time',
        'pickup_city',
        'event_name',
        'end_date',
        'rent',
        'city',
        'dropoff_date',
        'price_range',
        'venue',
        'appointment_date',
        'pickup_date',
        'pickup_time',
        'type',
        'rating',
        'phone_number',
        'passengers',
        'origin_airport_name',
        'has_live_music',
        'arrives_next_day',
        'transfers',
        'leaving_date',
        'price_per_night',
        'to_station',
        'therapist_name',
        'event_time',
        'show_type',
        'destination_city',
        'price_per_ticket',
        'intent',
        'from_station',
        'travelers',
        'free_entry',
        'subtitles',
        'humidity',
        'venue_address',
        'wind',
        'address_of_location',
        'event_location',
        'total_price',
        'new_alarm_time',
        'cuisine',
        'year',
        'origin_airport',
        'doctor_name',
        'new_alarm_name',
        'from',
        'seating_class',
        'title',
        'count',
        'star_rating',
        'number_of_rooms',
        'good_for_kids',
        'balance',
        'date',
        'inbound_departure_time',
        'num_passengers',
        'from_city',
        'recipient_account_name',
        'shared_ride',
        'movie_title',
        'outbound_arrival_time',
        'destination',
        'appointment_time',
        'cast',
        'device',
        'precipitation',
        'add_insurance',
        'receiver',
        'artist',
        'number_of_days',
        'number_of_beds',
        'event_type',
        'is_nonstop',
        'directed_by',
        'subtitle_language',
        'property_name',
        'city_of_event',
        'stay_length',
        'number_checked_bags',
        'destination_airport_name',
        'fare',
        'subcategory',
        'check_out_date',
        'address',
        'serves_alcohol',
        'origin_station_name',
        'available_start_time',
        'number_stops',
        'restaurant_name',
        'wait_time',
        'director',
        'average_rating',
        'flight_class',
        'number_of_baths',
        'recipient_account_type',
        'location',
        'alarm_time',
        'event_date',
        'departure_date',
        'to_location',
        'category',
        'playback_device',
        'attraction_name',
        'origin',
        'place_name',
        'destination_station_name',
        'hotel_name',
        'actors',
        'leaving_time',
        'ride_fare',
        'check_in_date',
        'ride_type',
        'amount',
        'additional_luggage',
        'date_of_journey',
        'to_city',
        'is_unisex',
        'contact_name',
        'outbound_departure_time',
        'has_seating_outdoors',
        'has_garage',
        'journey_start_time',
        'from_location',
        'departure_time',
        'offers_cosmetic_services',
        'start_date',
        'approximate_ride_duration',
        'number_of_riders',
        'group_size',
        'pets_welcome',
        'movie_name',
        'theater_name',
        'show_date',
        'genre',
        'smoking_allowed',
        'number_of_tickets',
        'destination_airport',
        'in_unit_laundry',
        'price_per_day',
        'is_redeye',
        'has_laundry_service',
        'temperature',
        'trip_protection',
        'alarm_name',
        'transfer_time',
        'total',
        'visit_date',
        'account_balance',
        'party_size',
        'stylist_name',
        'pets_allowed',
        'track',
        'payment_method',
        'pickup_location',
        'recipient_name',
        'car_type',
        'album',
        'inbound_arrival_time',
        'price',
        'starring',
        'private_visibility',
        'has_vegetarian_options',
        'available_end_time',
        'fare_type',
        'has_wifi',
        'car_name',
        'furnished',
        'origin_city',
        'airlines',
        'number_of_seats',
        'class',
        'where_to',
        'account_type',
        'to',
        'transfer_amount',
        'return_date',
        'area',
        'percent_rating',
        'dentist_name',
        'time',
        'method',
    ),
    'fa': (
        'تعداد_بزرگسالان',
        'نام_آهنگ',
        'قابل_استرداد',
        'رتبه_بندی_کل',
        'آدرس_خیابان',
        'زمان_نمایش',
        'شهر_وانت',
        'نام_رویداد',
        'تاریخ_پایان',
        'اجاره',
        'شهر',
        'تاریخ_افت',
        'محدوده_قیمت',
        'محل_برگزاری',
        'تاریخ_قرار',
        'تاریخ_وانت',
        'زمان_تحویل',
        'نوع',
        'رتبه_بندی',
        'شماره_تلفن',
        'مسافران',
        'نام_فرودگاه_مبدا',
        'دارای_موسیقی_زنده',
        'می_رسد_روز_دیگر',
        'انتقال',
        'تاریخ_ترک',
        'قیمت_هر_شب',
        'به_ایستگاه',
        'نام_درمانگر',
        'زمان_رویداد',
        'نوع_نمایش',
        'شهر_مقصد',
        'قیمت_هر_بلیط',
        'قصد',
        'از_ایستگاه',
        'مسافرین',
        'ورود_رایگان',
        'زیرنویس',
        'رطوبت',
        'آدرس_محل_برگزاری',
        'باد',
        'آدرس_مکان',
        'مکان_رویداد',
        'قیمت_کل',
        'زمان_هشدار_جدید',
        'آشپزی',
        'سال',
        'فرودگاه_مبدا',
        'نام_پزشک',
        'نام_هشدار_جدید',
        'از',
        'کلاس_نشستن',
        'عنوان',
        'تعداد',
        'رتبه_بندی_ستاره',
        'تعداد_اتاق',
        'خوب_برای_بچه_ها',
        'تعادل',
        'تاریخ',
        'زمان_عزیمت_ورودی',
        'تعداد_مسافران',
        'از_شهر',
        'نام_حساب_گیرنده',
        'سوار_مشترک',
        'عنوان_فیلم',
        'زمان_ورود_به_خارج',
        'مقصد',
        'زمان_قرار_ملاقات',
        'بازیگران',
        'دستگاه',
        'بارش',
        'اضافه_کردن_بیمه',
        'گیرنده',
        'هنرمند',
        'تعداد_روزها',
        'تعداد_تخت_ها',
        'نوع_رویداد',
        'بدون_توقف_است',
        'به_کارگردانی',
        'زبان_زیرنویس',
        'نام_ملک',
        'شهر_رویداد',
        'طول_اقامت',
        'تعداد_کیف_های_چک_شده',
        'نام_فرودگاه_مقصد',
        'کرایه',
        'زیر_مجموعه',
        'تاریخ_چک_کردن',
        'آدرس',
        'الکل_را_ارائه_می_دهد',
        'نام_ایستگاه_مبدا',
        'زمان_شروع_موجود',
        'تعداد_توقف',
        'نام_رستوران',
        'زمان_انتظار',
        'مدیر',
        'میانگین_امتیاز',
        'کلاس_پرواز',
        'تعداد_حمام',
        'نوع_حساب_گیرنده',
        'مکان',
        'زمان_هشدار',
        'تاریخ_رویداد',
        'تاریخ_عزیمت',
        'به_مکان',
        'دسته',
        'دستگاه_پخش',
        'نام_جاذبه',
        'مبدا',
        'نام_مکان',
        'نام_ایستگاه_مقصد',
        'نام_هتل',
        'بازیگرها',
        'زمان_ترک',
        'کرایه_سواری',
        'تاریخ_چک',
        'نوع_سواری',
        'مقدار',
        'چمدان_اضافی',
        'تاریخ_سفر',
        'به_شهر',
        'تک_جنسیتی_است',
        'نام_مخاطب',
        'ساعت_عزیمت_خروجی',
        'صندلی_در_فضای_باز',
        'دارای_گاراژ',
        'زمان_شروع_سفر',
        'از_محل',
        'زمان_عزیمت',
        'خدمات_آرایشی_را_ارائه_می_دهد',
        'تاریخ_شروع',
        'مدت_زمان_تقریبی_سوار_شدن',
        'تعداد_سوار',
        'اندازه_گروه',
        'حیوانات_خانگی_خوش_آمدید',
        'نام_فیلم',
        'نام_تئاتر',
        'تاریخ_نمایش',
        'ژانر',
        'سیگار_کشیدن_مجاز',
        'تعداد_بلیط',
        'فرودگاه_مقصد',
        'در_واحد_لباسشویی',
        'قیمت_روز',
        'قرمز_است',
        'خدمات_خشکشویی',
        'دما',
        'محافظت_از_سفر',
        'نام_زنگ_هشدار',
        'زمان_انتقال',
        'کل',
        'تاریخ_بازدید',
        'موجودی_حساب',
        'اندازه_مهمانی',
        'نام_سبک',
        'حیوانات_خانگی_مجاز_است',
        'مسیر',
        'روش_پرداخت',
        'محل_وانت',
        'نام_گیرنده',
        'نوع_خودرو',
        'آلبوم',
        'زمان_ورود_به_ورودی',
        'قیمت',
        'ستاره_دار',
        'دید_خصوصی',
        'گزینه_های_گیاهخواری_دارد',
        'زمان_پایان_موجود',
        'نوع_کرایه',
        'دارای_wifi',
        'نام_اتومبیل',
        'مبله',
        'شهر_مبدا',
        'خطوط_هوایی',
        'تعداد_صندلی_ها',
        'کلاس',
        'کجا',
        'نوع_حساب',
        'به',
        'مقدار_انتقال',
        'تاریخ_بازگشت',
        'منطقه',
        'درصد_امتیاز',
        'نام_دندانپزشک',
        'زمان',
        'روش',
    ),
}

MULTIWOZ_DOMAINS = {
    'en': ('attraction', 'bus', 'hospital', 'hotel', 'restaurant', 'taxi', 'train'),
    'fa': ("جاذبه", "اتوبوس", "بیمارستان", "هتل", "رستوران", "تاکسی", "قطار"),
    'zh': ("景点", "公共汽车", "医院", "旅馆", "餐厅", "出租车", "列车"),
    'it': ("attrazione", "bus", "ospedale", "hotel", "ristorante", "taxi", "treno"),
}

MULTIWOZ_SLOTS = {
    'en': (
        'area',
        'arrive by',
        'book day',
        'book people',
        'book stay',
        'book time',
        'day',
        'department',
        'departure',
        'destination',
        'food',
        'internet',
        'leave at',
        'leaveAt',
        'name',
        'parking',
        'price range',
        'stars',
        'type',
    ),
    'fa': (
        "منطقه",
        "رسیدن تا",
        "رزرو روز",
        "رزرو مردم",
        "رزرو اقامت",
        "رزرو زمان",
        "روز",
        "بخش",
        "عزیمت",
        "مقصد",
        "غذا",
        "اینترنت",
        "زمان ترک",
        "زمان ترک",
        "نام",
        "پارکینگ",
        "محدوده قیمت",
        "ستاره",
        "نوع",
    ),
    'zh': (
        '区域',
        '到达时间',
        '预订日期',
        '预订人数',
        '预订停留天数',
        '预订时间',
        '日期',
        '科室',
        '出发地',
        '目的地',
        '食物',
        '互联网',
        '出发时间',
        '出发时间',
        '名称',
        '停车处',
        '价格范围',
        '星级',
        '类型',
    ),
    'it': (
        "area",
        "arrivo entro",
        "prenota giorno",
        "prenota persone",
        "prenota soggiorno",
        "ora prenota",
        "giorno",
        "reparto",
        "partenza",
        "destinazione",
        "cibo",
        "internet",
        "leave at",
        "leaveAt",
        "name",
        "parking",
        "price range",
        "stars",
        "type",
    ),
}

RISAWOZ_DOMAINS = {
    'en': (
        'Tourist attractions',
        'restaurants',
        'hotels',
        'computers',
        'trains',
        'airplanes',
        'weather',
        'movies',
        'TV series',
        'tutorial classes',
        'cars',
        'hospitals',
    ),
    'zh': ('旅游景点', '餐厅', '酒店', '电脑', '火车', '飞机', '天气', '电影', '电视剧', '辅导班', '汽车', '医院'),
    'fa': (
        "جاذبه های گردشگری",
        "رستوران",
        "هتل",
        "رایانه",
        "قطار",
        "هواپیما",
        "هوا",
        "فیلم",
        "مجموعه های تلویزیونی",
        "کلاس های آموزشی",
        "اتومبیل",
        "بیمارستان",
    ),
    'uk': (
        "Туристичні визначні пам'ятки",
        'ресторани',
        'готелі',
        "комп'ютери",
        'поїзди',
        'літаки',
        'погода',
        'фільми',
        'серіали',
        'підручники',
        'машини',
        'лікарні',
    ),
    'sv': (
        'Turistattraktioner',
        'restauranger',
        'hotell',
        'datorer',
        'tåg',
        'flygplan',
        'väder',
        'filmer',
        'TV-serier',
        'handledningskurser',
        'bilar',
        'sjukhus',
    ),
    'fi': (
        "Matkailukohteet",
        "ravintolat",
        "hotellit",
        "tietokoneet",
        "junat",
        "lentokoneet",
        "sää",
        "elokuvat",
        "TV-sarjat",
        "oppitunnit",
        "autot",
        "sairaalat",
    ),
    'de': (
        "Touristenattraktionen",
        "Restaurants",
        "Hotels",
        "Computer",
        "Züge",
        "Flugzeuge",
        "Wetter",
        "Filme",
        "Fernsehserien",
        "Übungsklassen",
        "Autos",
        "Krankenhäuser",
    ),
}

RISAWOZ_SLOTS = {
    'en': (
        'Name',
        'Area',
        'Type of attraction',
        'Best for the crowd',
        'Consumption',
        'Whether the subway is directly accessible',
        'Ticket price',
        'Phone number',
        'Address',
        'Score',
        'Open Time',
        'Features',
        'Name',
        'Area',
        'Cuisine',
        'Price',
        'Whether the subway is directly accessible',
        'Per capita consumption',
        'Address',
        'Phone number',
        'Score',
        'Business hours',
        'Recommended dishes',
        'Name',
        'Area',
        'Star rating',
        'Price range',
        'Hotel type',
        'Room type',
        'Parking lot',
        'Room rate',
        'Address',
        'Phone number',
        'rating',
        'brand',
        'product category',
        'category',
        'memory capacity',
        'screen size',
        'CPU',
        'price range',
        'series',
        'product name',
        'system',
        'Game performance',
        'CPU model',
        'bare metal weight',
        'graphics card category',
        'graphics card model',
        'features',
        'color series',
        'standby time',
        'hard disk capacity',
        'price',
        'Departure Place',
        'Destination',
        'Date',
        'Model',
        'Seat',
        'Train Information',
        'Duration',
        'Departure Time',
        'Arrival Time',
        'Fare',
        'Departure Place',
        'Destination',
        'Date',
        'Class of Class',
        'Flight Information',
        'Departure Time',
        'Arrival Time',
        'Fare',
        'Punctuality',
        'City',
        'Date',
        'Weather',
        'Temperature',
        'Wind wind direction',
        'Ultraviolet intensity',
        'Production country/region',
        'Type',
        'Year',
        'Starring',
        'Director',
        'Title',
        'List of leading actors',
        'Specific release time',
        'length',
        'douban rating',
        'production country/region',
        'genre',
        'year',
        'leader',
        'director',
        'title',
        'list of lead actors',
        'First broadcast time',
        'episode number',
        'single episode length',
        'douban score',
        'class number',
        'difficulty',
        'subject',
        'grade',
        'area',
        'campus',
        'teaching method',
        'Start date',
        'End date',
        'Weekly',
        'Class time',
        'Class time',
        'Time period',
        'Class number',
        'Class hour',
        'Classroom location',
        'Teacher',
        'Price',
        'Course URL',
        'Teacher\'s URL',
        'Name',
        'Model',
        'Level',
        'Number of Seats',
        'Body Size (mm)',
        'Manufacturer',
        'Energy Type',
        'Engine Displacement (L)',
        'Engine horsepower (Ps)',
        'Driving mode',
        'Comprehensive fuel consumption (L/100km)',
        'Environmental protection standard',
        'Drive assist image',
        'Cruise system',
        'Price (ten thousand yuan)',
        'Car series',
        'Power level',
        'Fuel consumption level',
        'reversing image',
        'fixed speed cruise',
        'seat heating',
        'seat ventilation',
        'belonging to price range',
        'name',
        'grade',
        'category',
        'nature',
        'area',
        'Address',
        'Telephone',
        'Registration time',
        'Outpatient time',
        'Bus line',
        'Metro reachable',
        'Metro line',
        'Key department',
        'CT',
        '3.0T MRI',
        'DSA',
    ),
    'zh': (
        '名称',
        '区域',
        '景点类型',
        '最适合人群',
        '消费',
        '是否地铁直达',
        '门票价格',
        '电话号码',
        '地址',
        '评分',
        '开放时间',
        '特点',
        '名称',
        '区域',
        '菜系',
        '价位',
        '是否地铁直达',
        '人均消费',
        '地址',
        '电话号码',
        '评分',
        '营业时间',
        '推荐菜',
        '名称',
        '区域',
        '星级',
        '价位',
        '酒店类型',
        '房型',
        '停车场',
        '房费',
        '地址',
        '电话号码',
        '评分',
        '品牌',
        '产品类别',
        '分类',
        '内存容量',
        '屏幕尺寸',
        'CPU',
        '价格区间',
        '系列',
        '商品名称',
        '系统',
        '游戏性能',
        'CPU型号',
        '裸机重量',
        '显卡类别',
        '显卡型号',
        '特性',
        '色系',
        '待机时长',
        '硬盘容量',
        '价格',
        '出发地',
        '目的地',
        '日期',
        '车型',
        '坐席',
        '车次信息',
        '时长',
        '出发时间',
        '到达时间',
        '票价',
        '出发地',
        '目的地',
        '日期',
        '舱位档次',
        '航班信息',
        '起飞时间',
        '到达时间',
        '票价',
        '准点率',
        '城市',
        '日期',
        '天气',
        '温度',
        '风力风向',
        '紫外线强度',
        '制片国家/地区',
        '类型',
        '年代',
        '主演',
        '导演',
        '片名',
        '主演名单',
        '具体上映时间',
        '片长',
        '豆瓣评分',
        '制片国家/地区',
        '类型',
        '年代',
        '主演',
        '导演',
        '片名',
        '主演名单',
        '首播时间',
        '集数',
        '单集片长',
        '豆瓣评分',
        '班号',
        '难度',
        '科目',
        '年级',
        '区域',
        '校区',
        '上课方式',
        '开始日期',
        '结束日期',
        '每周',
        '上课时间',
        '下课时间',
        '时段',
        '课次',
        '课时',
        '教室地点',
        '教师',
        '价格',
        '课程网址',
        '教师网址',
        '名称',
        '车型',
        '级别',
        '座位数',
        '车身尺寸(mm)',
        '厂商',
        '能源类型',
        '发动机排量(L)',
        '发动机马力(Ps)',
        '驱动方式',
        '综合油耗(L/100km)',
        '环保标准',
        '驾驶辅助影像',
        '巡航系统',
        '价格(万元)',
        '车系',
        '动力水平',
        '油耗水平',
        '倒车影像',
        '定速巡航',
        '座椅加热',
        '座椅通风',
        '所属价格区间',
        '名称',
        '等级',
        '类别',
        '性质',
        '区域',
        '地址',
        '电话',
        '挂号时间',
        '门诊时间',
        '公交线路',
        '地铁可达',
        '地铁线路',
        '重点科室',
        'CT',
        '3.0T MRI',
        'DSA',
    ),
    'fa': (
        "نام",
        "منطقه",
        "نوع جاذبه",
        "بهترین حالت برای جمعیت",
        "مصرف",
        "آیا دسترسی مستقیم به مترو",
        "قیمت بلیط",
        "شماره تلفن",
        "آدرس",
        "امتیاز",
        "ساعات کاری ",
        "ویژگی ها",
        "نام",
        "منطقه",
        "آشپزی",
        "قیمت",
        "آیا مترو مستقیماً قابل دسترسی است",
        "مصرف سرانه",
        "آدرس",
        "شماره تلفن",
        "امتیاز",
        "ساعات کاری",
        "غذاهای توصیه شده",
        "نام",
        "منطقه",
        "ستاره",
        'قیمت',
        'نوع هتل',
        'نوع اتاق',
        'پارکینگ',
        'نرخ اتاق',
        'آدرس',
        "شماره تلفن",
        "امتیاز",
        "مارک",
        "گروه محصول",
        "طبقه بندی",
        "ظرفیت حافظه",
        "اندازه صفحه",
        "پردازنده",
        "محدوده قیمت",
        "سری",
        "نام محصول",
        "سیستم",
        "عملکرد بازی",
        "مدل CPU",
        "وزن فلز برهنه",
        "نوع کارت گرافیک",
        "مدل کارت گرافیک",
        "ویژگی ها",
        "سری رنگ",
        "زمان آماده به کار",
        "ظرفیت دیسک سخت",
        "قیمت",
        "عزیمت",
        "مقصد",
        "تاریخ",
        "مدل",
        "صندلی ",
        "اطلاعات قطار",
        "مدت زمان",
        "زمان عزیمت",
        "زمان ورود",
        "کرایه",
        "محل عزیمت",
        "مقصد",
        "تاریخ",
        "کلاس کلاس",
        "اطلاعات پرواز",
        "زمان عزیمت",
        "زمان ورود",
        "کرایه",
        "زمان دقت",
        "شهر",
        "تاریخ",
        "هوا",
        "دما",
        "جهت باد",
        "شدت فرابنفش",
        "کشور / منطقه تولید",
        "ژانر",
        "سال",
        "رهبر",
        "کارگردان",
        "عنوان",
        "لیست رهبران",
        "زمان اکران خاص",
        "طول",
        "رتبه بندی دوبان",
        "کشور تولید /منطقه ",
        "ژانر",
        "سال",
        "با بازی",
        "کارگردان",
        'عنوان',
        "لیست بازیگران برجسته",
        "زمان پخش اول",
        "تعداد قسمت ها",
        "طول قسمت تنها",
        "نمره دوبان",
        "شماره کلاس",
        "دشواری",
        "موضوع",
        "درجه",
        "منطقه",
        "پردیس",
        "روش کلاس",
        "تاریخ شروع",
        "تاریخ پایان",
        "هفتگی",
        "زمان کلاس",
        "زمان کلاس",
        "دوره زمانی",
        "اوقات کلاس",
        "ساعت کلاس",
        "مکان کلاس",
        "معلم",
        "قیمت",
        "URL دوره",
        "URL معلم",
        "نام",
        "مدل",
        "سطح",
        "تعداد صندلی ها",
        "اندازه بدنه (میلی متر)",
        "تولید کننده",
        "نوع انرژی",
        "جابجایی موتور (L)",
        "اسب بخار موتور (PS)",
        "حالت رانندگی",
        "مصرف سوخت جامع (L / 100 کیلومتر)",
        "استانداردهای زیست محیطی",
        "تصویر کمک رانندگی",
        "سیستم کروز",
        "قیمت (ده هزار یوان) ",
        "سری ماشین",
        "سطح قدرت ",
        "سطح مصرف سوخت",
        "عکس معکوس",
        "سرعت کروز",
        "گرم شدن صندلی",
        "تهویه صندلی",
        "محدوده قیمت",
        "نام",
        "درجه",
        "دسته",
        "طبیعت",
        "منطقه",
        "آدرس",
        "تلفن",
        "زمان ثبت نام",
        "سرپایی ",
        "خط اتوبوس",
        "مترو قابل دسترسی",
        "خط مترو",
        "بخشهای کلیدی",
        "CT",
        "3.0T MRI",
        "DSA",
    ),
    'uk': (
        "Ім'я",
        "Площа",
        "Тип атракціону",
        "Найкраще для натовпу",
        "Споживання",
        "Чи є метро безпосередньо доступним",
        "Ціна квитка",
        "Номер телефону",
        "Адреса",
        "Оцінка",
        'Години роботи',
        'особливості',
        'назва',
        'площа',
        'кухня',
        'ціна',
        "Чи є метро безпосередньо доступним",
        "Споживання на душу населення",
        "Адреса",
        "Номер телефону",
        "Оцінка",
        "Робочий час",
        "Рекомендовані страви",
        "Ім'я",
        "Площа",
        "Зірка",
        'Ціна',
        'Тип готелю',
        'Тип номера',
        'Стоянка',
        'Оплата за номер',
        'Адреса',
        'Номер телефону',
        'Оцінка',
        'Бренд',
        'Категорія товару',
        'Класифікація',
        "Об'єм пам'яті",
        'Розмір екрана',
        'Процесор',
        'Діапазон цін',
        'Серія',
        'Назва товару',
        'Система',
        'Продуктивність гри',
        'Модель процесора',
        'гола металева вага',
        'Тип графічної картки',
        'модель графічної карти',
        'особливості',
        'кольорова серія',
        'час очікування',
        'ємність жорсткого диска',
        'ціна',
        'відправлення',
        'призначення',
        'дата',
        'модель',
        'Місце',
        'Інформація про подорож',
        'Тривалість',
        'Час вильоту',
        'Час прибуття',
        'Вартість проїзду',
        'Місце вильоту',
        'Пункт призначення',
        'Дата',
        'Клас класу',
        'Інформація про рейс',
        'Час вильоту',
        'Час прибуття',
        'Вартість проїзду',
        'Рівень пунктуальності',
        'Місто',
        'Дата',
        'Погода',
        'Температура',
        'Напрямок вітру',
        'Інтенсивність ультрафіолету',
        'Країна / регіон виробництва',
        'жанр',
        'рік',
        'лідер',
        'режисер',
        'назва',
        'список провідних акторів',
        'конкретний час випуску',
        'тривалість',
        'рейтинг дубана',
        'Країна / регіон виробництва',
        "жанр",
        "рік",
        "головна роль",
        "режисер",
        'Назва',
        'Список провідних акторів',
        'Час першого ефіру',
        'Кількість серій',
        'Тривалість одного епізоду',
        'Бал Дубана',
        'Номер класу',
        'Складність',
        'Тема',
        'Оцінка',
        'Регіон',
        "Кампус",
        "Метод занять",
        "Дата початку",
        "Дата закінчення",
        "Щотижня",
        "Час заняття",
        'Час занять',
        'Час доби',
        'Час занять',
        'Години занять',
        'Розташування класу',
        'Вчитель',
        'Ціна',
        'URL-адреса курсу',
        'URL-адреса викладача',
        "Ім'я",
        'Модель',
        'Рівень',
        'Кількість місць',
        'Розмір кузова (мм)',
        'Виробник',
        'Тип енергії',
        "Робочий об'єм двигуна (L)",
        'Потужність двигуна (Ps)',
        'Режим руху',
        'Комплексне споживання палива (L / 100км)',
        'Екологічні норми',
        'Зображення допомоги при водінні',
        'Круїзна система',
        'Ціна (Десять тисяч юанів)',
        'автомобільна система',
        'рівень потужності',
        'рівень споживання палива',
        'Зворотне зображення',
        'Круїзний круїз',
        'обігрів сидінь',
        'вентиляція сидінь',
        'діапазон цін',
        'назва',
        'сорт',
        'категорія',
        'природа',
        'зона',
        'адреса',
        'телефон',
        'Реєстрація час',
        'Час амбулаторного лікування',
        'Автобусна лінія',
        'Доїзд до метро',
        'Лінія метро',
        'Ключові відділи',
        'КТ',
        '3,0 Т МРТ',
        'DSA',
    ),
    'sv': (
        'Namn',
        'Område',
        'Typ av attraktion',
        'Bäst för publiken',
        'Förbrukning',
        'Huruvida tunnelbanan är direkt tillgänglig',
        'Biljettpris',
        'Telefonnummer',
        'Adress',
        'Poäng',
        'Öppettider',
        'funktioner',
        'namn',
        'område',
        'kök',
        'pris',
        'Om tunnelbanan är direkt tillgänglig',
        'Per capita-förbrukning',
        'Adress',
        'Telefonnummer',
        'Poäng',
        'Öppettider',
        'Rekommenderade rätter',
        'Namn',
        'Område',
        'Stjärna',
        'Pris',
        'Hotelltyp',
        'rumstyp',
        'parkeringsplats',
        'rumsavgift',
        'adress',
        'Telefonnummer',
        'Poäng',
        'Märke',
        'Produktkategori',
        'Klassificering',
        'Minneskapacitet',
        'Skärmstorlek',
        'CPU',
        'Prisklass',
        'Serie',
        'Produktnamn',
        'System',
        'Spelprestanda',
        'CPU-modell',
        'bare metallvikt',
        'Grafikkorttyp',
        'grafikkortmodell',
        'funktioner',
        'färgserie',
        'standbytid',
        'hårddiskkapacitet',
        'pris',
        'avgång',
        'destination',
        'datum',
        'modell',
        'Sittplats',
        'Reseinformation',
        'Varaktighet',
        'Avgångstid',
        'Ankomsttid',
        'Pris',
        'Avgångsställe',
        'Destination',
        'Datum',
        'Klass av klass',
        'Flyginformation',
        'Avgångstid',
        'Ankomsttid',
        'Pris',
        'Punktlighet',
        'Stad',
        'Date',
        'Weather',
        'Temperature',
        'Wind Direction',
        'Ultraviolet Intensity',
        'Produktionsland / region',
        'genre',
        'år',
        'ledare',
        'regissör',
        'titel',
        'lista över ledande skådespelare',
        'specifik släpptid',
        'längd',
        'douban-betyg',
        'Produktionsland / region',
        'genre',
        'år',
        'medverkande',
        'regissör',
        'Titel',
        'Lista över ledande skådespelare',
        'Första sändningstid',
        'Antal avsnitt',
        'Längd för enstaka avsnitt',
        'Douban-poäng',
        'Klassnummer',
        'Svårighetsgrad',
        'Ämne',
        'Betyg',
        'Region',
        'Campus',
        'Klassmetod',
        'Startdatum',
        'Slutdatum',
        'Veckovis',
        'Klasstid',
        'Klass tid',
        'Tid på dagen',
        'Klass gånger',
        'Klass timmar',
        'Klassrumsplats',
        'Lärare',
        'Pris',
        'Kurs-URL',
        'Lärar-URL',
        'Namn',
        'Modell',
        'Nivå',
        'Antal sittplatser',
        'Kroppsstorlek (mm)',
        'Tillverkare',
        'Energityp',
        'Motorvolym (L)',
        'Motorhästkrafter (Ps)',
        'Körläge',
        'Omfattande bränsleförbrukning (L / 100 km)',
        'Miljöstandarder',
        'Körassistansbild',
        'Kryssningssystem',
        'Pris (Tiotusen yuan)',
        'bilsystem',
        'effektnivå',
        'bränsleförbrukningsnivå',
        'Omvänd bild',
        'Kryssningskryssning',
        'sätesuppvärmning',
        'sätesventilation',
        'prisklass',
        'namn',
        'klass',
        'kategori',
        'natur',
        'område',
        'adress',
        'telefon',
        'registrering tid',
        'Poliklinisk tid',
        'Busslinje',
        'Tunnelbana kan nås',
        'Subway Line',
        'Key Departments',
        'CT',
        '3.0T MRI',
        'DSA',
    ),
    'fi': (
        'Nimi',
        'Alue',
        'Nähtävyystyyppi',
        'Yleisölle parhaiten sopiva',
        'Kulutus',
        'Onko metroon pääsee suoraan',
        'Lippujen hinta',
        'Puhelinnumero',
        'Osoite',
        'Pisteet',
        'Aukioloajat',
        'ominaisuudet',
        'nimi',
        'alue',
        'keittiö',
        'hinta',
        'Pääsy metroon suoraan',
        'Kulutus asukasta kohti',
        'Osoite',
        'Puhelinnumero',
        'Pisteet',
        'Työajat',
        'Suositellut ruokalajit',
        'Nimi',
        'Alue',
        'Tähti',
        'Hinta',
        'Hotellityyppi',
        'Huonetyyppi',
        'Pysäköintialue',
        'Huonehinta',
        'Osoite',
        'Puhelinnumero',
        'Pisteet',
        'Tuotemerkki',
        'Tuoteryhmä',
        'Luokittelu',
        'Muistikapasiteetti',
        'Näytön koko',
        'Keskusyksikkö',
        'Hintaluokka',
        'Sarja',
        'Tuotteen nimi',
        'Järjestelmä',
        'Pelin suorituskyky',
        'Suorittimen malli',
        'paljaan metallin paino',
        'Grafiikkakortin tyyppi',
        'Graafisen kortin malli',
        'Ominaisuudet',
        'Värisarja',
        'Valmiustila',
        'Kiintolevyn kapasiteetti',
        'Hinta',
        'Lähtö',
        'Kohde',
        'Päivämäärä',
        'malli',
        'Istuin',
        'matkatiedot',
        'kesto',
        'lähtöaika',
        'saapumisaika',
        'Hinta',
        'Lähtöpaikka',
        'Kohde',
        'Päivämäärä',
        'Luokan luokka',
        'Lentotiedot',
        'Lähtöaika',
        'Saapumisaika',
        'Hinta',
        'täsmällisyysaste',
        'kaupunki',
        'Päivämäärä',
        'Sää',
        'Lämpötila',
        'Tuulen suunta',
        'Ultravioletti-intensiteetti',
        'Tuotantimaa / -alue',
        'genre',
        'vuosi',
        'johtaja',
        'ohjaaja',
        'otsikko',
        'luettelo johtavista toimijoista',
        'tietty julkaisuaika',
        'pituus',
        'douban-luokitus',
        'Tuotantomaa / -alue',
        'genre',
        'vuosi',
        'pääosissa',
        'ohjaaja',
        'Otsikko',
        'Luettelo johtavista toimijoista',
        'Ensimmäinen lähetysaika',
        'Jaksoiden määrä',
        'Yhden jakson pituus',
        'Douban-pisteet',
        'Luokan numero',
        'Vaikeus',
        'Aihe',
        'Arvosana',
        'Alue',
        'Kampus',
        'Luokan menetelmä',
        'Aloituspäivä',
        'Lopetuspäivä',
        'Viikoittain',
        'Luokan aika',
        'Kurssin aika',
        'Aikajakso',
        'Kurssin ajat',
        'Kurssitunnit',
        'Luokan sijainti',
        'Opettaja',
        'Hinta',
        'Kurssin URL',
        'Opettajan URL',
        'Nimi',
        'Malli',
        'Taso',
        'Istuinten lukumäärä',
        'Rungon koko (mm)',
        'Valmistaja',
        'Energiatyyppi',
        'Moottorin iskutilavuus (L)',
        'Moottorin hevosvoima (Ps)',
        'Ajotila',
        'Kattava polttoaineenkulutus (L / 100km)',
        'Ympäristötandardit',
        'Ajoapukuva',
        'Risteilyjärjestelmä',
        'Hinta (Kymmenentuhatta yuania)',
        'autojärjestelmä',
        'tehotaso',
        'polttoaineenkulutustaso',
        'Käänteinen kuva',
        'Risteilyristeily',
        'istuimenlämmitys',
        'istuimen tuuletus',
        'hintaluokka',
        'nimi',
        'luokka',
        'luokka',
        'luonto',
        'alue',
        'osoite',
        'puhelin',
        'rekisteröinti aika',
        'Avohoidon aika',
        'Linja-auto',
        'Metro saavutettavissa',
        'Metrolinja',
        'Keskeiset osastot',
        'CT',
        '3.0T MRI',
        'DSA',
    ),
    'de': (
        'Name',
        'Gebiet',
        'Art der Attraktion',
        'Best for the Crowd',
        'Consumption',
        "Ob die U-Bahn direkt erreichbar ist",
        "Ticketpreis",
        "Telefonnummer",
        "Adresse",
        'Score',
        'Open Time',
        'Features',
        'Name',
        'Area',
        'Cuisine',
        'Price',
        'Ob die U-Bahn direkt erreichbar ist',
        "Pro-Kopf-Verbrauch",
        "Adresse",
        "Telefonnummer",
        "Punktzahl",
        "Geschäftszeiten",
        "Empfohlene Gerichte",
        'Name',
        'Fläche',
        'Sternebewertung',
        'Preisspanne',
        'Hoteltyp',
        'Zimmertyp',
        'Parkplatz',
        'Zimmerpreis',
        'Adresse',
        'Telefonnummer',
        'Bewertung',
        'Marke',
        'Produktkategorie',
        'Kategorie',
        'Speicherkapazität',
        'Bildschirmgröße',
        'CPU',
        'Preisspanne',
        'Serie',
        'Produktname',
        'System',
        'Spieleleistung',
        'CPU-Modell',
        "Bare-Metal-Gewicht",
        "Grafikkartenkategorie",
        "Grafikkartenmodell",
        "Funktionen",
        'Farbserie',
        'Standby-Zeit',
        'Festplattenkapazität',
        'Preis',
        'Abflugort',
        'Ziel',
        'Datum',
        "Modell",
        "Sitz",
        'Zuginformationen',
        'Dauer',
        'Abfahrtszeit',
        'Ankunftszeit',
        'Fahrpreis',
        'Abfahrtsort',
        'Ziel',
        'Datum',
        'Klassenklasse',
        'Fluginformationen',
        'Abflugzeit',
        'Ankunftszeit',
        'Tarif',
        'Pünktlichkeit',
        "Stadt",
        "Datum",
        "Wetter",
        "Temperatur",
        "Windwindrichtung",
        "UV-Intensität",
        'Produktionsland / Region',
        'Typ',
        'Jahr',
        'Darsteller',
        'Regisseur',
        'Titel',
        'Liste der Hauptdarsteller',
        "Spezifische Veröffentlichungszeit",
        "Länge",
        "Douban-Bewertung",
        "Produktionsland / -region",
        "Genre",
        'Jahr',
        'Führer',
        "Regisseur",
        "Titel",
        "Liste der Hauptdarsteller",
        "Erste Sendezeit",
        "Episodennummer",
        'Länge einer einzelnen Episode',
        'Douban Score',
        'Klassennummer',
        'Schwierigkeitsgrad',
        'Fach',
        'Klasse',
        "Bereich",
        "Campus",
        'Unterrichtsmethode',
        'Startdatum',
        'Enddatum',
        'Wöchentlich',
        'Unterrichtszeit',
        'Unterrichtszeit',
        'Zeitraum',
        'Klassennummer',
        'Unterrichtsstunde',
        'Unterrichtsort',
        'Lehrer',
        'Preis',
        'Kurs-URL',
        'URL des Lehrers',
        'Name',
        'Modell',
        'Stufe',
        'Anzahl der Sitze',
        'Körpergröße (mm)',
        'Hersteller',
        'Energietyp',
        'Hubraum (L)',
        'Motorleistung (Ps)',
        'Fahrmodus',
        "Umfassender Kraftstoffverbrauch (L / 100 km)",
        "Umweltschutznorm",
        'Drive Assist Image',
        "Kreuzfahrtsystem",
        "Preis (zehntausend Yuan)",
        "Autoserie",
        "Leistungsstufe",
        'Kraftstoffverbrauchsniveau',
        "Bild umkehren",
        "Kreuzfahrt mit fester Geschwindigkeit",
        "Sitzheizung",
        "Sitzbelüftung",
        "Zugehörigkeit zur Preisspanne",
        'Name',
        'Klasse',
        'Kategorie',
        'Natur',
        'Gebiet',
        'Adresse',
        'Telefon',
        'Registrierungszeit',
        "Ambulante Zeit",
        "Buslinie",
        "U-Bahn erreichbar",
        "U-Bahnlinie",
        "Schlüsselabteilung",
        "CT",
        "3.0T MRI",
        "DSA",
    ),
}
